### ISSUE TITLE
Unable to get this working in Unity 2019.2.15f

### ISSUE THREAD

**Issue by XcomReborn** [Synthoid/UnitySubstanceExtensions#2]
I have dragged the plugin folder into my asset folder but it will not compile.

First Error I get complains of a problem copying a Multiplayer HLAPI dll file. So I googled that and people suggested removing the Multiplayer HLAPI package and reinstalling it.

After doing so this error goes away and is replaced by 6 new compile errors complaining error CS0246 the type or namespace 'Substance' could not be found.

I've had so many problem with Substance in unity I just want to export all my substance textures to png's and then never have to use it again. But I can't seem to do this.

**Comment by Synthoid** [comment]
You have to install the Substance plugin for the extension classes to work. They cannot function by themselves.

This code hasn’t really been updated for a while, but the newest substance plugin supports exporting all the generated bitmaps for a substance out of the box. I recommend installing that then exporting your maps, or just exporting your maps in Substance Player.

It is a shame that the plugin has so many flaws. I hope you can get everything exported!
